services:
  postgres:
    container_name: postgres
    working_dir: /usr/
    image: postgres
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_HOST}
    ports:
      - 5432:5432
    volumes:
      - ./volumes/tables.sql:/docker-entrypoint-initdb.d/tables.sql
